name: First Workflow
on: [push]

jobs: 
    run-jobs:
        runs-on: ubuntu-latest
        steps:
            - name: echo a string
              run: echo "Hello World"
            - name: Multiline command
              run: |
                python -v
                node -v